version: '3.8'

services:
  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: isidevops
      MYSQL_USER: root
    ports:
      - "3306:3306"
    networks:
      - microservices-network

  microservice-gestion-cours:
    build: ./microservice-gestion-cours
    ports:
      - "9001:9001"
    environment:
      - SERVER_PORT=9001
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/isidevops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql-db
    networks:
      - microservices-network

  microservice-gestion-prof:
    build: ./microservice-gestion-prof
    ports:
      - "9002:9002"
    environment:
      - SERVER_PORT=9002
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/isidevops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql-db
    networks:
      - microservices-network

  microservice-gestion-etudiant:
    build: ./microservice-gestion-etudiant
    ports:
      - "9003:9003"
    environment:
      - SERVER_PORT=9003
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/isidevops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql-db
    networks:
      - microservices-network

  microservice-gestion-classe:
    build: ./microservice-gestion-classe
    ports:
      - "9004:9004"
    environment:
      - SERVER_PORT=9004
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/isidevops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql-db
    networks:
      - microservices-network

  microservice-gestion-emploi-du-temp:
    build: ./microservice-gestion-emploi-du-temp
    ports:
      - "9005:9005"
    environment:
      - SERVER_PORT=9005
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/isidevops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql-db
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
