on:
  push:
    branches: [ develop, staging ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

- name: Build and push Docker images
  run: |
    # Build et push frontend
    if [ -d "frontenddevops" ]; then
      echo "Building frontend Docker image"
      docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest" ./frontenddevops
      docker push "${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest"
    fi

    # Build et push microservices
    declare -A services=(
      ["microservice-gestion-cours"]="9001"
      ["microservice-gestion-prof"]="9002"
      ["microservice-gestion-etudiant"]="9003"
      ["microservice-gestion-classe"]="9004"
      ["microservice-gestion-emploi-du-temp"]="9005"
    )

    for service in "${!services[@]}"; do
      if [ -d "$service" ]; then
        SERVICE_NAME=$(echo $service | cut -d'-' -f3-)
        echo "Building $service"
        docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:latest" ./$service
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:latest"
      fi
    done 