name: CI/CD Pipeline with Monitoring

on:
  push:
    branches: [ main, master, develop, staging ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  test-and-quality:
    name: Tests et Qualité
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Configuration Java pour Spring Boot
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Tests et Installation des Microservices
    - name: Initialize Maven Wrapper and Build & Test Microservice Cours
      run: |
        if [ ! -d "microservice-gestion-cours" ]; then
          echo "Creating microservice-gestion-cours directory"
          mkdir microservice-gestion-cours
          cd microservice-gestion-cours
          mvn -N wrapper:wrapper
        else
          cd microservice-gestion-cours
        fi
        chmod +x mvnw
        ./mvnw clean install
        ./mvnw test

    - name: Initialize Maven Wrapper and Build & Test Microservice Professeur
      run: |
        if [ ! -d "microservice-gestion-professeur" ]; then
          echo "Creating microservice-gestion-professeur directory"
          mkdir microservice-gestion-professeur
          cd microservice-gestion-professeur
          mvn -N wrapper:wrapper
        else
          cd microservice-gestion-professeur
        fi
        chmod +x mvnw
        ./mvnw clean install
        ./mvnw test

    - name: Initialize Maven Wrapper and Build & Test Microservice Etudiant
      run: |
        if [ ! -d "microservice-gestion-etudiant" ]; then
          echo "Creating microservice-gestion-etudiant directory"
          mkdir microservice-gestion-etudiant
          cd microservice-gestion-etudiant
          mvn -N wrapper:wrapper
        else
          cd microservice-gestion-etudiant
        fi
        chmod +x mvnw
        ./mvnw clean install
        ./mvnw test

    - name: Initialize Maven Wrapper and Build & Test Microservice Classe
      run: |
        if [ ! -d "microservice-gestion-classe" ]; then
          echo "Creating microservice-gestion-classe directory"
          mkdir microservice-gestion-classe
          cd microservice-gestion-classe
          mvn -N wrapper:wrapper
        else
          cd microservice-gestion-classe
        fi
        chmod +x mvnw
        ./mvnw clean install
        ./mvnw test

    - name: Initialize Maven Wrapper and Build & Test Microservice Emploi du Temps
      run: |
        if [ ! -d "microservice-gestion-emploi-temps" ]; then
          echo "Creating microservice-gestion-emploi-temps directory"
          mkdir microservice-gestion-emploi-temps
          cd microservice-gestion-emploi-temps
          mvn -N wrapper:wrapper
        else
          cd microservice-gestion-emploi-temps
        fi
        chmod +x mvnw
        ./mvnw clean install
        ./mvnw test
        
    # Configuration Node.js pour Angular    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontenddevops/package-lock.json
        
    # Installation Frontend (Angular)
    - name: Install Frontend Dependencies
      run: |
        cd frontenddevops
        npm install -g @angular/cli
        npm ci
        
    # Tests Frontend (Angular)
    - name: Run Frontend Tests
      run: |
        cd frontenddevops
        npm test -- --watch=false --browsers=ChromeHeadless
        
    # Analyse de qualité
    - name: Code Quality Analysis
      run: |
        cd frontenddevops
        npm run lint || true
        for service in microservice-gestion-*; do
          cd $service
          ./mvnw checkstyle:check || true
          cd ..
        done

  build-and-package:
    name: Build et Packaging
    needs: test-and-quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Build Backend Services
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build Microservices
      run: |
        for service in microservice-gestion-*; do
          cd $service
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          cd ..
        done
        
    # Build Frontend    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Build Frontend
      run: |
        cd frontenddevops
        npm install -g @angular/cli
        npm ci
        ng build --configuration=production
        
    # Package as artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: |
          microservice-gestion-*/target/*.jar
          frontenddevops/dist
        compression-level: 0
        retention-days: 5
        
    # Build Docker Images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker images
      run: |
        # Build Frontend
        docker build -f frontenddevops/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

        # Configuration des microservices avec leurs ports
        declare -A services=(
          ["microservice-gestion-cours"]="9001"
          ["microservice-gestion-professeur"]="9002"
          ["microservice-gestion-etudiant"]="9003"
          ["microservice-gestion-classe"]="9004"
          ["microservice-gestion-emploi-temps"]="9005"
        )

        # Build et push pour chaque microservice
        for service in "${!services[@]}"; do
          PORT="${services[$service]}"
          SERVICE_NAME=$(echo $service | cut -d'-' -f3-)
          
          echo "Building $service on port $PORT"
          
          # Build avec le port configuré
          docker build -f $service/Dockerfile \
            --build-arg PORT=$PORT \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:${{ github.sha }} \
            ./$service
          
          # Push des images
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE_NAME:${{ github.sha }}
        done

  deploy-dev:
    name: Deploy to Development
    if: github.ref == 'refs/heads/develop'
    needs: build-and-package
    runs-on: ubuntu-latest
    environment:
      name: development
      url: http://dev-app.example.com
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: app-build
        path: app-build
        
    - name: Deploy to Dev Environment
      run: |
        echo "Déploiement des microservices en environnement de développement"
        # Ajoutez ici vos commandes de déploiement

  deploy-prod:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: build-and-package
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://devops-ci-cd.onrender.com
    
    steps:
    - name: Deploy to Production
      uses: JorgeLNJunior/render-deploy@v1.4.3
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        wait_deploy: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

  monitoring:
    name: Application Monitoring
    needs: [deploy-dev, deploy-prod]
    runs-on: ubuntu-latest
    
    steps:
    - name: Check Application Health
      run: |
        echo "Vérification de la santé des microservices"
        # Ajoutez ici vos commandes de monitoring 

    - name: Deploy Services
      run: |
        # Création du docker-compose pour le déploiement
        cat > docker-compose.yml <<EOF
        version: '3'
        services:
          frontend:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ports:
              - "80:80"
            depends_on:
              - cours
              - professeur
              - etudiant
              - classe
              - emploi-temps

          cours:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/cours:latest
            ports:
              - "9001:9001"
            environment:
              - SERVER_PORT=9001
              
          professeur:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/professeur:latest
            ports:
              - "9002:9002"
            environment:
              - SERVER_PORT=9002
              
          etudiant:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/etudiant:latest
            ports:
              - "9003:9003"
            environment:
              - SERVER_PORT=9003
              
          classe:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/classe:latest
            ports:
              - "9004:9004"
            environment:
              - SERVER_PORT=9004
              
          emploi-temps:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/emploi-temps:latest
            ports:
              - "9005:9005"
            environment:
              - SERVER_PORT=9005
        EOF
